# Generated by Django 3.2.5 on 2021-09-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_refundrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequests',
            name='reason',
            field=models.CharField(default=0.00029688273132112816, max_length=200),
            preserve_default=False,
        ),
    ]
