# Generated by Django 3.2.5 on 2021-09-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_favorite_favoriteitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteitem',
            name='order_number',
        ),
        migrations.AddField(
            model_name='favoriteitem',
            name='product_id',
            field=models.CharField(default=0.0002619553511657013, max_length=50),
            preserve_default=False,
        ),
    ]
