# Generated by Django 3.2.5 on 2021-09-16 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210913_1354'),
        ('accounts', '0009_auto_20210917_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteitem',
            name='product_id',
        ),
        migrations.AddField(
            model_name='favoriteitem',
            name='product',
            field=models.ForeignKey(default=0.0002619553511657013, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
    ]
