# Generated by Django 3.2.5 on 2021-09-19 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210917_0130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refundrequests',
            options={'verbose_name': 'Refund Request', 'verbose_name_plural': 'Refund Requests'},
        ),
    ]
