# Generated by Django 3.2.5 on 2021-09-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='rating',
            field=models.IntegerField(default=0.00022266204849084612),
            preserve_default=False,
        ),
    ]
