# Generated by Django 3.2.5 on 2021-09-19 17:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0011_viewedproducts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ViewedProducts',
            new_name='ViewedProduct',
        ),
    ]
