# Generated by Django 3.2.5 on 2021-09-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210313_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='state',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tax',
            new_name='shipping_fee',
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(default=0.0003425569976782248, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='street_name',
            field=models.CharField(default=0.0003425569976782248, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='unit',
            field=models.CharField(default=0.0003425569976782248, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('To Ship', 'To Ship'), ('To Receive', 'To Receive'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='To Ship', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
