# Generated by Django 3.2.5 on 2021-09-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_shipping_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='estimated_delivery',
            field=models.CharField(default=0.0003425569976782248, max_length=100),
            preserve_default=False,
        ),
    ]
