# Generated by Django 3.2.5 on 2021-11-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20211006_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vouchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_name', models.CharField(max_length=125)),
                ('voucher_code', models.CharField(max_length=20)),
                ('discount', models.FloatField()),
            ],
        ),
    ]
