# Generated by Django 3.2.5 on 2021-11-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_vouchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
